channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.2.2
- pip:
  - mlflow==2.21.3
  - cloudpickle==2.0.0
  - lz4==3.1.3
  - numpy==1.21.5
  - pandas==2.2.3
  - pathlib==1.0.1
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
